# Generated by Django 6.0.4 on 2026-04-19 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendors', models.ManyToManyField(blank=True, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REMEDIATED', 'Remediated'), ('NA', 'Not Applicable')], default='OPEN', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vulnerability')),
            ],
            options={
                'unique_together': {('profile', 'vulnerability')},
            },
        ),
    ]
