# Generated by Django 6.0.4 on 2026-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vulnerabilitystatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sla_critical',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sla_high',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sla_low',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sla_medium',
            field=models.IntegerField(default=60),
        ),
    ]
